export const FETCH_MOVIES_BY_GENRE_REQUEST = 'FETCH_MOVIES_BY_GENRE_REQUEST';
export const FETCH_MOVIES_BY_GENRE_SUCCESS = 'FETCH_MOVIES_BY_GENRE_SUCCESS';
export const FETCH_MOVIES_BY_GENRE_ERROR = 'FETCH_MOVIES_BY_GENRE_ERROR';

export const FETCH_MOVIE_BY_ID_REQUEST = 'FETCH_MOVIES_BY_ID_REQUEST';
export const FETCH_MOVIE_BY_ID_SUCCESS = 'FETCH_MOVIES_BY_ID_SUCCESS';
export const FETCH_MOVIE_BY_ID_ERROR = 'FETCH_MOVIES_BY_ID_ERROR';

export const FETCH_MOVIES_BY_DATA_REQUEST = 'FETCH_MOVIES_BY_DATA_REQUEST';
export const FETCH_MOVIES_BY_DATA_SUCCESS = 'FETCH_MOVIES_BY_DATA_SUCCESS';
export const FETCH_MOVIES_BY_DATA_ERROR = 'FETCH_MOVIES_BY_DATA_ERROR';
